version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
    
hooks:
 ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root
 ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: validate_server.sh
      timeout: 300
      runas: root
